/**
 * Unified Signal Processing Pipeline
 * Agent 6: Single entry point for all signal processing
 */

import { TradingViewSignal } from '../types';
import { GeneratedSignal } from './signal-generator.service';
import { SignalProcessorService, ProcessedSignal } from './signal-processor.service';
import { autoTradeManager } from './auto-trade-manager';
import pool from '../db';

export class UnifiedPipelineService {
  private signalProcessor: SignalProcessorService;

  constructor() {
    // Will be initialized with services from manager
    this.signalProcessor = new SignalProcessorService();
  }

  async initialize(): Promise<void> {
    await autoTradeManager.initialize();
    
    // Update signal processor with services
    this.signalProcessor = new SignalProcessorService(
      autoTradeManager.getOrchestrator(),
      autoTradeManager.getStrikeSelector(),
      autoTradeManager.getMarketData()
    );
  }

  /**
   * Process signal from any source (webhook, signal generator, etc.)
   */
  async processSignal(
    signal: TradingViewSignal | GeneratedSignal,
    source: 'webhook' | 'auto-generated' | 'manual'
  ): Promise<ProcessedSignal> {
    await this.initialize();
    return await this.signalProcessor.processSignal(signal, source);
  }

  /**
   * Process webhook signal specifically
   */
  async processWebhookSignal(signal: TradingViewSignal): Promise<ProcessedSignal> {
    return await this.processSignal(signal, 'webhook');
  }

  /**
   * Process auto-generated signal
   */
  async processAutoGeneratedSignal(signal: GeneratedSignal): Promise<ProcessedSignal> {
    return await this.processSignal(signal, 'auto-generated');
  }
}

export const unifiedPipeline = new UnifiedPipelineService();


